# Generated by Django 3.1.1 on 2021-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('descrip', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='api',
        ),
    ]
